//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apitcceletroEntities : DbContext
    {
        public apitcceletroEntities()
            : base("name=apitcceletroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barras> barras { get; set; }
        public virtual DbSet<pessoas> pessoas { get; set; }
        public virtual DbSet<simulacoes> simulacoes { get; set; }
        public virtual DbSet<simulacoes_ppu> simulacoes_ppu { get; set; }
    }
}
