//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pessoas()
        {
            this.simulacoes = new HashSet<simulacoes>();
        }
    
        public int id { get; set; }
        public string tipodepessoa { get; set; }
        public string nome { get; set; }
        public string documento { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<System.DateTime> datadecriacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simulacoes> simulacoes { get; set; }
    }
}
