//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class simulacoes_ppu
    {
        public int id { get; set; }
        public Nullable<int> idsimulacao { get; set; }
        public Nullable<int> quantidade { get; set; }
        public Nullable<double> potencia { get; set; }
    
        public virtual simulacoes simulacoes { get; set; }
    }
}
