//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simulacoes()
        {
            this.Simulacoes_ppu = new HashSet<Simulacoes_ppu>();
        }
    
        public int id { get; set; }
        public Nullable<int> idPessoa { get; set; }
        public string Nome { get; set; }
        public Nullable<double> Potencia { get; set; }
        public string Barra { get; set; }
        public string Endereco { get; set; }
        public Nullable<double> Tensao { get; set; }
        public string Sistema { get; set; }
        public Nullable<double> NivelCC { get; set; }
        public Nullable<int> Nota { get; set; }
        public Nullable<System.DateTime> DatadaSimulacao { get; set; }
        public Nullable<int> DadosComplementares { get; set; }
        public Nullable<int> SolicitacaodeAcesso { get; set; }
    
        public virtual Pessoas Pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Simulacoes_ppu> Simulacoes_ppu { get; set; }
    }
}
