//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class simulacoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public simulacoes()
        {
            this.simulacoes_ppu = new HashSet<simulacoes_ppu>();
        }
    
        public int id { get; set; }
        public Nullable<int> idpessoa { get; set; }
        public string nome { get; set; }
        public Nullable<double> potencia { get; set; }
        public string barra { get; set; }
        public string endereco { get; set; }
        public Nullable<double> tensao { get; set; }
        public string sistema { get; set; }
        public Nullable<double> nivelcc { get; set; }
        public Nullable<int> nota { get; set; }
        public Nullable<System.DateTime> datadasimulacao { get; set; }
        public Nullable<int> dadoscomplementares { get; set; }
        public Nullable<int> solicitacaodeacesso { get; set; }
    
        public virtual pessoas pessoas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<simulacoes_ppu> simulacoes_ppu { get; set; }
    }
}
