//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEletroposto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trechos
    {
        public long id { get; set; }
        public string Trecho { get; set; }
        public string Barra1 { get; set; }
        public string Barra2 { get; set; }
    }
}
