//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCCELETROPOSTOEntities : DbContext
    {
        public TCCELETROPOSTOEntities()
            : base("name=TCCELETROPOSTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barras> Barras { get; set; }
        public virtual DbSet<Pessoas> Pessoas { get; set; }
        public virtual DbSet<Simulacoes> Simulacoes { get; set; }
        public virtual DbSet<Simulacoes_ppu> Simulacoes_ppu { get; set; }
        public virtual DbSet<Trechos> Trechos { get; set; }
    }
}
